version: '3.8'

services:
  app:
    image: hwayoung311/synapse:latest
    container_name: synapse
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://synapse-db:3306/synapse?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=synapse
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_REDIS_HOST=synapse-redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: synapse-db
    restart: always
    environment:
      MYSQL_DATABASE: synapse
      MYSQL_USER: synapse
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:7
    container_name: synapse-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
